(() => {
const root='./', $=id=>document.getElementById(id);
let language='en',food=2,cut=0,step=0,page=0;
const tr=(en,zh)=>language==='en'?en:zh;
const foods=[
 {id:'potato',name:['Potato','土豆'],title:['A steady day','平平常常的一天'],story:['Classes, errands, the journey home. Nothing terrible happened. Nothing wonderful, either. You kept going.','上课、待办、回家的路。没有坏事发生，也没有什么惊喜。你就这样撑过了一天。'],whisper:['Even an ordinary day can feel heavy.','平凡的一天，也可能很沉。'],images:['014','015','016','017'],cuts:['Big chunks','Thin slices','Small cubes','Mash it'],zhcuts:['切大块','切薄片','切小丁','压成泥'],meanings:['Face it head on','Lay everything out','One small step','Let it all go'],zhmeanings:['正面面对','一件件摊开','一小步就好','暂时放下'],responses:['You pushed the feelings down until they stopped making noise. Now you give them a little room.','“Don’t worry.” “I’m fine.” Laid side by side, the things you said start to sound different.','Maybe things don’t need to be solved all at once. Start with one small piece.','For tonight, you don’t want to think about it anymore. Let the day be done.'],zhresponses:['那些被压下去的感受安静了很久。现在，给它们留一点位置。','“别担心。”“我没事。”把这些话放在一起，才听见另一种意思。','也许不需要一次解决所有事情。从一小块开始就好。','今晚，你不想再想了。让这一天先结束吧。']},
 {id:'mushroom',name:['Mushroom','蘑菇'],title:['A little too much absorbed','吸收了太多心事'],story:['An offhand comment. A change in someone’s tone. You brought them home without meaning to.','一句随口的话，一点语气的变化。不知不觉，你把它们都带回了家。'],whisper:['Not everything is yours to carry.','有些心事，不必由你来背。'],images:['023','024','025','026'],cuts:['Big chunks','Thin slices','Tear apart','Leave whole'],zhcuts:['切大块','切薄片','撕开','保持完整'],meanings:['Keep a little space','See it clearly','Put it down','Stay as you are'],zhmeanings:['留一点距离','看清它','放下来','允许自己如此'],responses:['Bigger pieces leave a little space. You don’t have to soak up every feeling around you.','A comment, a tone, a story you imagined. Looking at each piece makes it easier to understand.','A sharp motion, almost freeing. Maybe these feelings were never yours to carry.','You know you absorbed too much. But some sensitivity is simply part of you.'],zhresponses:['大一点的块，留下一点空间。不必吸收身边的每一种情绪。','一句评价，一种语气，一个想象的故事。分开来看，就清楚了一点。','一下撕开，像松了一口气。这些感受，也许本来就不属于你。','你知道自己吸收了太多。但敏感，也是你的一部分。']},
 {id:'tomato',name:['Tomato','番茄'],title:['Messages unsent','那些没发出去的话'],story:['A friend in another city. A message written, rewritten, deleted. In the end, you only tapped a heart.','住在另一座城市的朋友。一条消息，写了又改，改了又删。最后，你只点了一颗心。'],whisper:['You had more to say.','其实，你还有好多话想说。'],images:['033','034','035','036'],cuts:['Big chunks','Thin slices','Small cubes','Crush it'],zhcuts:['切大块','切薄片','切小丁','压碎'],meanings:['A little honesty','Look at the words','Say a little first','Let it spill'],zhmeanings:['坦诚一点','看看那些话','先说一点','让它流出来'],responses:['You did want to reach out. Admitting that much is a beginning.','All those messages you rewrote. Your care was never as small as the reply you sent.','You don’t have to say everything at once. One small message can be enough.','The juice spills out. For a moment, you stop trying to keep everything neatly inside.'],zhresponses:['你确实想靠近某个人。承认这一点，就是一个开始。','那些反复修改的消息。你的在意，从来不只有发出去的那几个字。','不必一次说完所有的话。一条小小的消息，也可以。','汁水流出来了。这一刻，不用再把所有感受收得整整齐齐。']},
 {id:'tofu',name:['Tofu','豆腐'],title:['Holding it together','小心维持的平静'],story:['You rehearsed the sentence before speaking. Chose the emoji twice. Said “anything is fine” when it wasn’t.','开口前反复练习一句话。选了又选回复的表情。明明有想法，还是说了“都可以”。'],whisper:['Being calm takes work, too.','保持平静，也很费力。'],images:['043','044','045','046'],cuts:['Big pieces','Fine strips','Small cubes','Leave whole'],zhcuts:['切大块','切细条','切小丁','保持完整'],meanings:['Make room','Show a soft edge','Just a little','Hold gently'],zhmeanings:['留出空间','露出柔软的一面','只表达一点','轻轻托住'],responses:['You let a little of what you feel become visible. It doesn’t have to be perfect.','The delicate strips tremble. Showing something fragile can feel like this.','Small pieces are easier to hold. Expressing a little is enough for today.','No cuts. No breakage. Some days, holding yourself together takes all your strength.'],zhresponses:['让一点真实的感受被看见。不必表现得完美。','细细的豆腐条轻轻颤动。展示脆弱时，也许就是这种感觉。','小块更容易托住。今天表达一点点，就已经够了。','不切开，不打碎。有些日子，维持自己就已经用尽了力气。']},
 {id:'carrot',name:['Carrot','胡萝卜'],title:['Softness given away','给出去的温柔'],story:['You helped a friend. Looked something up for your family. Said “I can do it” one more time. And what about you?','帮朋友解答问题，为家人查资料。又一次说“我来吧”。那么，你自己呢？'],whisper:['Save a little kindness for yourself.','也给自己留一点温柔。'],images:['053','054','055','056'],cuts:['Big chunks','Thin slices','Small cubes','Fine shreds'],zhcuts:['切大块','切薄片','切小丁','切细丝'],meanings:['For you, too','Notice your care','Save some energy','Your way of caring'],zhmeanings:['也分给自己','看见自己的付出','留一点力气','你的关心方式'],responses:['You were kind to everyone today. Make a little room for yourself at the table.','Each slice looks like one small act of care. You can be generous and tired at the same time.','Pull back a little. Your kindness doesn’t have to be constant, and it doesn’t have to be big.','Fine shreds take patience. Giving what you can is a familiar way of caring.'],zhresponses:['今天你对每个人都很好。也在餐桌上，给自己留一个位置。','每一片都像一次小小的付出。温柔和疲惫，可以同时存在。','收回一点力气。你的善意不必时刻在线，也不必很大。','切细丝需要耐心。尽力给予，是你熟悉的关心方式。']}
];
const stages=[
 ['Ingredients','食材','What stayed with you?','什么留在了心里？','Two main ingredients carry the feelings at the heart of the day. A side ingredient brings in a quieter feeling.','两种主食材承载一天里最主要的感受，配料则带入那些更细微的情绪。','22','Start with what is here.','从眼前的感受开始。'],
 ['Cut','切配','How do you approach it?','你想怎样面对？','Cutting, slicing, or leaving something whole becomes a choice about how much you are ready to face.','切块、切片，或保持完整，对应着此刻你愿意面对多少。','034','A choice made by hand.','用双手做一个选择。'],
 ['Side ingredients','配料','And the smaller things?','还有那些小事呢？','Ginger, onion, and green pepper make room for swallowed anger, a tender spot, and the irritation you cannot quite name.','生姜、洋葱、青椒，对应咽下去的愤怒、被触碰的柔软，以及说不清的烦躁。','061','The things between the lines.','藏在话语之间。'],
 ['Heat','火候','Will you give it time?','愿意给它一点时间吗？','Simmer, stir-fry, steam, or bake. The cooking method gives the story a different pace and a different way of responding.','慢炖、快炒、清蒸或烘烤。烹饪方式带来不同的节奏，也带来不同的回应。','071','Some things soften slowly.','有些东西，慢慢才会变软。'],
 ['Season','调味','How much is enough?','多少才刚好？','Choose salt, sugar, pepper, or vinegar, then decide how much to add. Small amounts can change the taste of a day.','选盐、糖、胡椒或醋，再决定加入多少。小小的分量，也能改变一天的滋味。','075','A little changes a lot.','一点点，也有不同。'],
 ['Serve','上桌','A dish of your day.','属于今天的料理。','The two main ingredients come together in the final dish. The story ends with a meal, and an invitation to begin again.','两种主食材组成最后的料理。故事以一顿饭收尾，也邀请你再次开始。','083','No perfect dish required.','不需要做得完美。']
];
function animate(el,cls='swap'){el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function renderFoods(){ $('ingredient-shelf').innerHTML=foods.map((f,i)=>`<button class="ingredient" data-food="${i}" aria-pressed="${i===food}"><img src="${root+f.id}.png" alt=""><span>${f.name[language==='en'?0:1]}</span></button>`).join('');const f=foods[food],n=language==='en'?0:1;$('picked-food').src=root+f.id+'.png';$('picked-food').alt=f.name[n];$('food-number').textContent=`0${food+1} / 05`;$('food-label').textContent=f.name[n].toUpperCase();$('food-title').textContent=f.title[n];$('food-story').textContent=f.story[n];$('food-whisper').textContent=f.whisper[n];renderCut();}
function renderCut(){const f=foods[food],labels=language==='en'?f.cuts:f.zhcuts;$('cut-options').innerHTML=labels.map((label,i)=>`<button data-cut="${i}" aria-pressed="${i===cut}">${label}</button>`).join('');$('cut-image').src=root+'scenes/'+f.images[cut]+'.webp';$('cut-image').alt=f.name[language==='en'?0:1]+' — '+labels[cut];$('cut-caption').textContent=(f.name[language==='en'?0:1]+' / '+labels[cut]).toUpperCase();$('cut-meaning').textContent=(language==='en'?f.meanings:f.zhmeanings)[cut];$('cut-story').textContent=(language==='en'?f.responses:f.zhresponses)[cut];}
function renderStep(){const n=language==='en'?0:1;$('steps').innerHTML=stages.map((s,i)=>`<button data-step="${i}" aria-pressed="${i===step}"><span>0${i+1}</span>${s[n]}</button>`).join('');const s=stages[step];$('step-title').textContent=s[2+n];$('step-description').textContent=s[4+n];$('step-note').textContent=s[7+n];$('step-image').src=root+'scenes/'+s[6]+'.webp';$('step-image').alt=s[n];}
$('ingredient-shelf').addEventListener('click',e=>{const b=e.target.closest('[data-food]');if(!b)return;food=Number(b.dataset.food);cut=0;renderFoods();animate($('picked-food'));animate(document.querySelector('.note'));});
$('cut-options').addEventListener('click',e=>{const b=e.target.closest('[data-cut]');if(!b)return;cut=Number(b.dataset.cut);renderCut();animate($('cut-image'));animate(document.querySelector('.cut-response'));});
$('steps').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(!b)return;step=Number(b.dataset.step);renderStep();animate(document.querySelector('.process-detail'));});
$('lang').onclick=()=>{language=language==='en'?'zh':'en';document.documentElement.lang=language==='en'?'en':'zh-CN';document.querySelectorAll('[data-en]').forEach(el=>{el.innerHTML=el.dataset[language]});$('lang').textContent=language==='en'?'中文':'EN';renderFoods();renderStep();updateSound();};
const bgm=$('bgm');bgm.volume=.22;function updateSound(){$('sound').textContent=bgm.paused?tr('Sound off','声音关'):tr('Sound on','声音开');$('sound').setAttribute('aria-pressed',String(!bgm.paused));} $('sound').onclick=async()=>{if(bgm.paused){try{await bgm.play();}catch{$('sound').textContent=tr('Audio unavailable','声音暂不可用');return;}}else bgm.pause();updateSound();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
const nav=document.querySelector('nav');function updateNav(){nav.classList.toggle('scrolled',scrollY>document.querySelector('.hero').offsetHeight-130);}addEventListener('scroll',updateNav,{passive:true});addEventListener('pageshow',updateNav);addEventListener('resize',updateNav);updateNav();renderFoods();renderStep();
})();

